import type { FooterColumnWithLinks } from './types';

export const DEFAULT_FOOTER_SETTING = {
  id: 'default',
  logoUrl: '/api/uploads/placeholder.png',
  logoAlt: 'RaYnk Labs',
  copyrightText: `All Right Reserved \u00a9 ${new Date().getFullYear()}`,
  address: 'RaYnk Labs, India',
  email: 'hello@raynklabs.com',
  phone: '+91 98765 43210',
  phoneLabel: '',
  updatedAt: new Date(0),
};

export const DEFAULT_FOOTER_COLUMNS: FooterColumnWithLinks[] = [
  {
    id: 'fallback-services',
    title: 'OUR SERVICES',
    sortOrder: 0,
    isVisible: true,
    createdAt: new Date(0),
    updatedAt: new Date(0),
    links: [
      {
        id: 'fallback-services-web',
        columnId: 'fallback-services',
        title: 'Web Development',
        href: '/services#section2-services-grid',
        sortOrder: 0,
        isVisible: true,
      },
      {
        id: 'fallback-services-ui',
        columnId: 'fallback-services',
        title: 'UI/UX Design',
        href: '/services#section3-services-benefits',
        sortOrder: 1,
        isVisible: true,
      },
      {
        id: 'fallback-services-seo',
        columnId: 'fallback-services',
        title: 'SEO & Growth',
        href: '/services#section4-services-work-process',
        sortOrder: 2,
        isVisible: true,
      },
      {
        id: 'fallback-services-ai',
        columnId: 'fallback-services',
        title: 'AI Solutions',
        href: '/services',
        sortOrder: 3,
        isVisible: true,
      },
    ],
  },
  {
    id: 'fallback-company',
    title: 'COMPANY',
    sortOrder: 1,
    isVisible: true,
    createdAt: new Date(0),
    updatedAt: new Date(0),
    links: [
      {
        id: 'fallback-company-about',
        columnId: 'fallback-company',
        title: 'About Us',
        href: '/about',
        sortOrder: 0,
        isVisible: true,
      },
      {
        id: 'fallback-company-team',
        columnId: 'fallback-company',
        title: 'Team',
        href: '/team',
        sortOrder: 1,
        isVisible: true,
      },
      {
        id: 'fallback-company-portfolio',
        columnId: 'fallback-company',
        title: 'Portfolio',
        href: '/portfolio',
        sortOrder: 2,
        isVisible: true,
      },
      {
        id: 'fallback-company-contact',
        columnId: 'fallback-company',
        title: 'Contact',
        href: '/contact',
        sortOrder: 3,
        isVisible: true,
      },
    ],
  },
  {
    id: 'fallback-resources',
    title: 'RESOURCES',
    sortOrder: 2,
    isVisible: true,
    createdAt: new Date(0),
    updatedAt: new Date(0),
    links: [
      {
        id: 'fallback-resources-blog',
        columnId: 'fallback-resources',
        title: 'Blog',
        href: '/blog',
        sortOrder: 0,
        isVisible: true,
      },
      {
        id: 'fallback-resources-case',
        columnId: 'fallback-resources',
        title: 'Case Studies',
        href: '/portfolio#section4-case-studies',
        sortOrder: 1,
        isVisible: true,
      },
      {
        id: 'fallback-resources-faq',
        columnId: 'fallback-resources',
        title: 'FAQ',
        href: '/contact#section5-faq',
        sortOrder: 2,
        isVisible: true,
      },
    ],
  },
  {
    id: 'fallback-community',
    title: 'COMMUNITY',
    sortOrder: 3,
    isVisible: true,
    createdAt: new Date(0),
    updatedAt: new Date(0),
    links: [
      {
        id: 'fallback-social-github',
        columnId: 'fallback-community',
        title: 'GitHub',
        href: 'https://github.com/rohitrathod1',
        sortOrder: 0,
        isVisible: true,
      },
      {
        id: 'fallback-social-linkedin',
        columnId: 'fallback-community',
        title: 'LinkedIn',
        href: 'https://www.linkedin.com/company/raynk-labs',
        sortOrder: 1,
        isVisible: true,
      },
      {
        id: 'fallback-social-instagram',
        columnId: 'fallback-community',
        title: 'Instagram',
        href: 'https://www.instagram.com/raynklabs',
        sortOrder: 2,
        isVisible: true,
      },
      {
        id: 'fallback-social-youtube',
        columnId: 'fallback-community',
        title: 'YouTube',
        href: 'https://www.youtube.com/@raynklabs',
        sortOrder: 3,
        isVisible: true,
      },
    ],
  },
  {
    id: 'fallback-quick',
    title: 'QUICK LINKS',
    sortOrder: 4,
    isVisible: true,
    createdAt: new Date(0),
    updatedAt: new Date(0),
    links: [
      {
        id: 'fallback-quick-home',
        columnId: 'fallback-quick',
        title: 'Home',
        href: '/',
        sortOrder: 0,
        isVisible: true,
      },
      {
        id: 'fallback-quick-services',
        columnId: 'fallback-quick',
        title: 'Services',
        href: '/services',
        sortOrder: 1,
        isVisible: true,
      },
      {
        id: 'fallback-quick-contact',
        columnId: 'fallback-quick',
        title: 'Start a Project',
        href: '/contact#section2-contact-form',
        sortOrder: 2,
        isVisible: true,
      },
    ],
  },
];

export const FOOTER_SOCIAL_TITLES = [
  'github',
  'linkedin',
  'instagram',
  'youtube',
  'twitter',
  'x',
  'facebook',
];
